# Generated by Django 4.2.7 on 2023-12-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('School_location', models.CharField(max_length=100)),
                ('school_principal', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='webpages',
            name='topic_name',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpages',
        ),
    ]
